USE hrqueue_db;



INSERT INTO categories (category)
VALUES
('Beneficiaries'),
('Career Guidance'),
('Direct Deposit'),
('Disciplinary Issue'),
('Employee Information Change'),
('Employee Offboarding'),
('Employee Onboarding'),
('Employment Verification'),
('General'),
('Grievance'),
('Leave'),
('Medical/Dental/Vision/Pharmacy'),
('Other'),
('Payroll'),
('Retirement'),
('Tuition Reimbursement'),
('Vacation');

INSERT INTO departments (department)
VALUES
('Animal Care Services'),
('Arts & Culture'),
('Aviation'),
('Building & Equipment Services'),
('Center City Development & Operations'),
('City Attorney'),
('City Auditor'),
('City Clerk'),
('City Council\'s Office'),
('City Manager\'S Office'),
('Convention & Sports Facilities'),
('Development Services'),
('Economic Development'),
('Emergency Management'),
('Equity'),
('Finance'),
('Fire'),
('Government & Public Affairs'),
('Health'),
('Historic Preservation'),
('Human Resources'),
('Human Services'),
('Information Technology Services'),
('Innovation'),
('Library'),
('Management & Budget'),
('Mayor\'S Office'),
('Municipal Court'),
('Neighborhood & Housing Services'),
('Parks & Recreation'),
('Planning'),
('Police'),
('Pre-K 4 SA'),
('Risk Management'),
('Solid Waste Management'),
('Sustainability'),
('Transportation & Capital Improvements'),
('Tricentennial Commission'),
('World Heritage');