USE hrqueue_db;


INSERT INTO categories (category)
VALUES
('Beneficiaries'),
('Career Guidance'),
('Direct Deposit'),
('Disciplinary Issue'),
('Employee Information Change'),
('Employee Offboarding'),
('Employee Onboarding'),
('Employment Verification'),
('General'),
('Grievance'),
('Leave'),
('Medical/Dental/Vision/Pharmacy'),
('Other'),
('Payroll'),
('Retirement'),
('Tuition Reimbursement'),
('Vacation');

INSERT INTO departments (department)
VALUES
('ANIMAL CARE SERVICES'),
('ARTS & CULTURE'),
('AVIATION'),
('BUILDING AND EQUIPMENT SERVICES'),
('CENTER CITY DEVELOPMENT AND OPERATIONS'),
('CITY ATTORNEY'),
('CITY AUDITOR'),
('CITY CLERK'),
('CITY COUNCIL\'S OFFICE'),
('CITY MANAGER\'S OFFICE'),
('CONVENTION & SPORTS FACILITIES'),
('DEVELOPMENT SERVICES'),
('ECONOMIC DEVELOPMENT'),
('EMERGENCY MANAGEMENT'),
('EQUITY'),
('FINANCE'),
('FIRE'),
('GOVERNMENT & PUBLIC AFFAIRS'),
('HEALTH'),
('HISTORIC PRESERVATION'),
('HUMAN RESOURCES'),
('HUMAN SERVICES'),
('INFORMATION TECHNOLOGY SERVICES'),
('INNOVATION'),
('LIBRARY'),
('MANAGEMENT & BUDGET'),
('MAYOR\'S OFFICE'),
('MUNICIPAL COURT'),
('NEIGHBORHOOD & HOUSING SERVICES'),
('PARKS & RECREATION'),
('PLANNING'),
('POLICE'),
('PRE-K 4 SA'),
('RISK MANAGEMENT'),
('SOLID WASTE MANAGEMENT'),
('SUSTAINABILITY'),
('TRANSPORTATION & CAPITAL IMPROVEMENTS'),
('TRICENTENNIAL COMMISSION'),
('WORLD HERITAGE');